### ISSUE TITLE
Invariant for magic getters

### ISSUE THREAD

**Issue by SerafimArts** [php-deal/framework#14]
`@Contract\Invariant("$this->some")` does not work if `some` field will be taken via magic getter `__get`. Its very popular solution for ActiveRecord libraries, like Eloquent or Yii1\2 AR and AnalogueOrm (DataMapper).

Error:

```
ErrorException (E_WARNING)
array_combine(): Both parameters should have an equal number of elements.

In ~/src/Aspect/AbstractContractAspect.php on line 46
```

**Comment by lisachenko** [comment]
Could you please add before `array_combine` a line that will var_dump both arguments. Then, add an information about method signature and list of DbC contracts for that method, as well as class contracts

**Comment by lisachenko** [comment]
BTW, an invariant contract for magic properties - it's pretty strange )

**Comment by SerafimArts** [comment]
This will be fix this =)
```php
    protected function fetchMethodArguments(MethodInvocation $invocation)
    {
        $parameters = $invocation->getMethod()->getParameters();

        $argumentNames = array_map(function (\ReflectionParameter $parameter) {
            return $parameter->name;
        }, $parameters);

        $parameters = [];
        $argumentValues = $invocation->getArguments();

        foreach ($argumentNames as $i => $name) {
            $parameters[$name] = isset($argumentValues[$i]) 
                ? $argumentValues[$i]
                : null;
        }


        return $parameters;
    }
```

**Comment by lisachenko** [comment]
Fixed in https://github.com/php-deal/framework/commit/f934d91f2b510608e792bed0c6fe8dd1d4a0a44e
