### ISSUE TITLE
ZF2 Module

### ISSUE THREAD

**Issue by icanhazstring** [php-deal/framework#16]
Hi,

i implemented a ZF2-Module for php-deal using goaop-zf2-module.
Would be nice if you can link this inside you readme.

Maybe a new colab under "php-deal" would be nice.
So we can group everything together like under goaop.

```
php-deal/framework
php-deal/php-deal-zf2
```

As an example.
But we don't have to :)

Greets

**Comment by lisachenko** [comment]
Hi!

Just created https://github.com/php-deal/php-deal-zf2-module. Later I will move my repo to this organization as a framework package

**Comment by lisachenko** [comment]
Transferred `lisachenko/php-deal` to the `php-deal/framework` package )

**Comment by lisachenko** [comment]
FYI, you have write permission to the https://github.com/php-deal/php-deal-zf2-module/ repository and can publish/register packet/advertise your module for ZF2 )

**Comment by icanhazstring** [comment]
@lisachenko 

```
remote: Permission to php-deal/php-deal-zf2-module.git denied to icanhazstring.
fatal: unable to access 'https://github.com/php-deal/php-deal-zf2-module/': The requested URL returned error: 403
```

**Comment by lisachenko** [comment]
@icanhazstring approved your assignment to the team, now you should be able to push

**Comment by icanhazstring** [comment]
@lisachenko works thanks. Will update README.md as soon as i find the time. Thanks

**Comment by icanhazstring** [comment]
@lisachenko updated and ready to go. Thanks :)
