### ISSUE TITLE
Contract propagation for interfaces

### ISSUE THREAD

**Issue by pdaw** [php-deal/framework#17]
Analogously to https://github.com/php-deal/framework/issues/9 that to would be nice to support propagation of interfaces' contracts. Currently, only classes are supported.

**Comment by lisachenko** [comment]
Agree that contract propagation for interfaces should also work, but not sure if I'll be able to implement this myself, almost haven't time for my open-source projects (

**Comment by pdaw** [comment]
I will find some time in a few days (:

**Comment by lisachenko** [comment]
Implemented in #20

**Comment by lisachenko** [comment]
👍
