### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by pdaw** [php-deal/framework#18]
To provide a foothold for potential contributors. It may be easy, even similar to https://github.com/joke2k/faker/blob/master/CONTRIBUTING.rst for example.

**Comment by lisachenko** [comment]
Hi! It would be nice to have this guide on board )

**Comment by lisachenko** [comment]
Added in https://github.com/php-deal/framework/commit/7b4039a0f55045190b6ef25e353c8d19939e1775

**Comment by pdaw** [comment]
Nice to see this project active again, it needs some love 👍
