### ISSUE TITLE
Library name in Scrutinizer and Packagist

### ISSUE THREAD

**Issue by pdaw** [php-deal/framework#19]
To be consistent, scrutinizer-ci.com/g/**lisachenko/php-deal** and packagist.org/packages/**lisachenko/php-deal** should be renamed or a new project should be created :)

**Comment by lisachenko** [comment]
https://packagist.org/packages/php-deal/framework

**Comment by lisachenko** [comment]
https://scrutinizer-ci.com/g/php-deal/framework/

**Comment by lisachenko** [comment]
Done
