### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by lukenm** [php-deal/framework#22]
Hi Alexander,

I'm interested in this project, but having issues with the way the exceptions are being displayed. What's the status? No commits for 2 years?

If you're still working on it, I will add some more detail.

Cheers,
Luke.

**Comment by lisachenko** [comment]
Hi, @lukenm! Project is still maintained, but I'm lack of time for OSS and concentrated on `goaop` framework itself, so no significant changes in this repo.

But I like this project, it deserves some love and enhancements. 
It would be nice to elect maintainers and give them admin rights on this repo.

**Comment by pdaw** [comment]
Hello @lukenm and @lisachenko (after a long break :D). You can describe the issue and we will take a look, I like the project and can spare some time for it.

**Comment by lukenm** [comment]
HI @pdaw @lisachenko, thanks, I will add separate issues for the problems I am having.

**Comment by icanhazstring** [comment]
Will close this as duplicate to #24
