### ISSUE TITLE
Defining Expression Handlers

### ISSUE THREAD

**Issue by ssamran15** [php-deal/framework#6]
Thanks @lisachenko its really a great help to understand and use this library. I have few questions.
1)- Where are the expression handlers defined or in other words which Class/File is handling the Expressions (@Contract\Verify("$amount>0 && is_numeric($amount)"))
2)- How complex expressions we can specify?
3)- How i can introduce my custom expression handlers?

many thanks in advance

**Comment by lisachenko** [comment]
Hello, @ssamran15 

1) This is called "an advice" in the terms of AOP. And advice is defined as a closure or a method inside an aspect. For PhpDeal this logic is stored in the one single aspect, check this method or just put a breakpoint in it: https://github.com/lisachenko/php-deal/blob/master/src/PhpDeal/Aspect/ContractCheckerAspect.php#L45-L68
2) PhpDeal allows any valid expressions, they will be evaluated as a traditional code via closures. So you can put there anything you want, however I want to recommend simple expressions, as this can be easy to understand and to validate.
3) With Go! AOP you can create your own joinpoints, pointcuts and aspects for them. So just create a custom annotation, an aspect and register in the aspect kernel. PhpDeal registers an aspect there: https://github.com/lisachenko/php-deal/blob/master/src/PhpDeal/ContractApplication.php, you can extend this class and override `configureAop` method to add custom aspects.

**Comment by lisachenko** [comment]
Closing this issue, because it's typical support, no additional code changes are required.
